/**
 * Publication-ready export (v2). Produces a clean, white, print-optimised
 * report document (→ "Save as PDF" in the browser print dialog) and CSV
 * downloads. Figures are embedded as high-resolution PNG data URLs captured
 * from the live ECharts instances.
 */

export interface ReportSection {
  title: string;
  /** Key/value rows rendered as a definition grid. */
  rows?: [string, string][];
  /** A full table. */
  table?: { headers: string[]; rows: string[][] };
  /** An embedded figure (PNG data URL). */
  figure?: string;
  note?: string;
}

export interface ReportDoc {
  title: string;
  subtitle?: string;
  author: string;
  meta: [string, string][];
  sections: ReportSection[];
}

function esc(s: string): string {
  return s.replace(
    /[&<>"]/g,
    (c) =>
      (({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }) as Record<
        string,
        string
      >)[c],
  );
}

function sectionHtml(s: ReportSection): string {
  let body = "";
  if (s.rows?.length) {
    body += `<dl class="grid">${s.rows
      .map(
        ([k, v]) =>
          `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`,
      )
      .join("")}</dl>`;
  }
  if (s.table) {
    body += `<table><thead><tr>${s.table.headers
      .map((h) => `<th>${esc(h)}</th>`)
      .join("")}</tr></thead><tbody>${s.table.rows
      .map(
        (r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`,
      )
      .join("")}</tbody></table>`;
  }
  if (s.figure) {
    body += `<img class="figure" src="${s.figure}" alt="${esc(s.title)}" />`;
  }
  if (s.note) body += `<p class="note">${esc(s.note)}</p>`;
  return `<section><h2>${esc(s.title)}</h2>${body}</section>`;
}

export function openPrintableReport(doc: ReportDoc): void {
  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) {
    alert("Please allow pop-ups to export the report.");
    return;
  }
  const html = `<!doctype html><html><head><meta charset="utf-8" />
<title>${esc(doc.title)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, "Times New Roman", serif; color: #111827;
    background: #fff; margin: 0; padding: 48px 56px; line-height: 1.5; }
  header { border-bottom: 2px solid #111827; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 24px; margin: 0 0 4px; }
  .subtitle { color: #4b5563; font-size: 14px; margin: 0; }
  .meta { display: flex; flex-wrap: wrap; gap: 6px 28px; margin-top: 12px;
    font-family: ui-sans-serif, system-ui, sans-serif; font-size: 12px; color: #6b7280; }
  .meta b { color: #111827; font-weight: 600; }
  section { margin: 24px 0; page-break-inside: avoid; }
  h2 { font-size: 15px; font-family: ui-sans-serif, system-ui, sans-serif;
    text-transform: uppercase; letter-spacing: .06em; color: #374151;
    border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
  dl.grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px 18px;
    font-family: ui-sans-serif, system-ui, sans-serif; }
  dl.grid dt { font-size: 10px; text-transform: uppercase; letter-spacing: .05em; color: #6b7280; }
  dl.grid dd { margin: 2px 0 0; font-size: 16px; font-weight: 600; font-variant-numeric: tabular-nums; }
  table { width: 100%; border-collapse: collapse; font-family: ui-sans-serif, system-ui, sans-serif;
    font-size: 12px; font-variant-numeric: tabular-nums; }
  th, td { border: 1px solid #e5e7eb; padding: 6px 10px; text-align: right; }
  th:first-child, td:first-child { text-align: left; }
  thead th { background: #f3f4f6; }
  .figure { max-width: 100%; border: 1px solid #e5e7eb; border-radius: 6px; margin-top: 8px; }
  .note { font-family: ui-sans-serif, system-ui, sans-serif; font-size: 11px; color: #6b7280; }
  footer { margin-top: 36px; border-top: 1px solid #e5e7eb; padding-top: 10px;
    font-family: ui-sans-serif, system-ui, sans-serif; font-size: 10px; color: #9ca3af; }
  @media print { body { padding: 24px; } }
</style></head>
<body>
  <header>
    <h1>${esc(doc.title)}</h1>
    ${doc.subtitle ? `<p class="subtitle">${esc(doc.subtitle)}</p>` : ""}
    <div class="meta">${doc.meta
      .map(([k, v]) => `<span><b>${esc(k)}:</b> ${esc(v)}</span>`)
      .join("")}</div>
  </header>
  ${doc.sections.map(sectionHtml).join("")}
  <footer>Generated by Strata — Scientific Data Workspace · ${esc(
    new Date().toLocaleString(),
  )}</footer>
  <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 350); };</script>
</body></html>`;
  win.document.write(html);
  win.document.close();
}

/** Download a CSV file built from a 2-D array. */
export function downloadCSV(filename: string, rows: (string | number)[][]): void {
  const csv = rows
    .map((r) =>
      r
        .map((cell) => {
          const s = String(cell);
          return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
        })
        .join(","),
    )
    .join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
